In [7]:
#load the data
import numpy as np
import pandas as pd
import random
import mir_utils as miru
import sounddevice as sd
import matplotlib.pyplot as plt

from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

testFraction=0.4

In [18]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

df=pd.read_csv("feat_frequency_bins.csv")
#preperocessing
le = preprocessing.LabelEncoder()
le.fit(df.label)
le.transform(df.label)
df.label=le.transform(df.label)
print(np.sum(df.dtypes!=np.float64)) #make sure this is 1, our label column is string
#df.label=le.inverse_transform(df.label) #inverse of transform if u need it

X=df.loc[:,df.columns!="label"]
y=df["label"]


1


In [19]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=testFraction, random_state=42)
classifier =   RandomForestClassifier(max_depth=10, n_estimators=20, max_features=2)
classifier.fit(X_train, y_train,)

from sklearn.metrics import classification_report, confusion_matrix

y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(le.inverse_transform(y_test),le.inverse_transform(y_pred)))

[[ 78   2   5  21   0]
 [  3 231   4  21  12]
 [  0   3  18  15   1]
 [ 15  20   6 253   4]
 [  3  35   1  14  13]]
              precision    recall  f1-score   support

  hihat_open       0.79      0.74      0.76       106
        kick       0.79      0.85      0.82       271
         rim       0.53      0.49      0.51        37
       snare       0.78      0.85      0.81       298
    tom_high       0.43      0.20      0.27        66

    accuracy                           0.76       778
   macro avg       0.67      0.62      0.63       778
weighted avg       0.74      0.76      0.75       778

